openapi: 3.0.0
info:
  title: Events API
  version: "1.0.0"
servers:
  - url: http://localhost:8080
paths:
  /events:
    get:
      summary: Get All Events
      responses:
        '200':
          description: A list of events.
    post:
      summary: Create Event
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                datetime:
                  type: string
                  format: date-time
                location:
                  type: string
              example:
                name: "Samay Show 3"
                description: "Samay's comedy show"
                datetime: "2024-08-12T15:30:00.00Z"
                location: "Delhi"
      responses:
        '201':
          description: Event created
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Event created successfully!"
  /events/{id}:
    get:
      summary: Get Event
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Event details
    put:
      summary: Update Event
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                datetime:
                  type: string
                  format: date-time
                location:
                  type: string
              example:
                name: "Samay Show 2"
                description: "Samay's comedy show"
                datetime: "2024-08-20T15:30:00.00Z"
                location: "Pune"
      responses:
        '200':
          description: Event updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Event updated successfully!"
    delete:
      summary: Delete Event
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Event deleted
  /signup:
    post:
      summary: Sign up
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              example:
                email: "user2@email.com"
                password: "password"
      responses:
        '200':
          description: User signed up
  /login:
    post:
      summary: Login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              example:
                email: "user2@email.com"
                password: "password"
      responses:
        '200':
          description: User logged in
  /events/{id}/register:
    post:
      summary: Register for an event
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Registered for the event
    delete:
      summary: Cancel Registration
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Registration canceled
